export const closeout = {
  step: 1,
  houseCount: 0,
  ticketTurnbacks: 0,
  noShows: 0,
  onlineSales: 0,
  doorSales: 0,
  totalTicketsSold: 0,
  ticketSales: 0,
  ticketSalesTax: 0,
  bandPayment: 0,
  barPayment: 0,
  doorPayment: 0,
  parkingPayment: 0,
  photographyPayment: 0,
  soundPayment: 0,
  otherPayment: 0,
  barSales: 0,
  merchSales: 0,
  posterSales: 0,
  barMerchReceipts: 0,
  barMerchSales: 0,
  barMerchTax: 0,
  totalWithdrawal: 0,
  barBank: 0,
  bandDeposit: 0,
  totalSales: 0,
  totalExpenses: 0,
  totalDeposit: 0,
  totalProfit: 0,
  submitted: false,
};

export const closeoutTest1 = {
  step: 4,
  houseCount: 0,
  ticketTurnbacks: 0,
  noShows: 0,
  onlineSales: 2750,
  doorSales: 0,
  totalTicketsSold: 0,
  ticketSales: 0,
  ticketSalesTax: 0,
  bandPayment: 1575,
  barPayment: 50,
  doorPayment: 0,
  parkingPayment: 20,
  photographyPayment: 0,
  soundPayment: 0,
  otherPayment: 0,
  barSales: 0,
  merchSales: 40,
  posterSales: 35,
  barMerchReceipts: 0,
  barMerchSales: 0,
  barMerchTax: 0,
  totalWithdrawal: 1825,
  barBank: 250,
  bandDeposit: 525,
  totalSales: 0,
  totalExpenses: 0,
  totalDeposit: 1330,
  totalProfit: 0,
  submitted: false,
};

export const closeoutTest2 = {
  step: 4,
  houseCount: 0,
  ticketTurnbacks: 0,
  noShows: 0,
  onlineSales: 2640,
  doorSales: 0,
  totalTicketsSold: 0,
  ticketSales: 0,
  ticketSalesTax: 0,
  bandPayment: 1615,
  barPayment: 0,
  doorPayment: 0,
  parkingPayment: 20,
  photographyPayment: 25,
  soundPayment: 0,
  otherPayment: 0,
  barSales: 1317,
  merchSales: 170,
  posterSales: 54,
  barMerchReceipts: 0,
  barMerchSales: 0,
  barMerchTax: 0,
  totalWithdrawal: 1500,
  barBank: 300,
  bandDeposit: 285,
  totalSales: 0,
  totalExpenses: 0,
  totalDeposit: 0,
  totalProfit: 0,
  submitted: false,
};
export const closeoutTest3 = {
  step: 4,
  houseCount: 0,
  ticketTurnbacks: 0,
  noShows: 0,
  onlineSales: 2640,
  doorSales: 0,
  totalTicketsSold: 0,
  ticketSales: 0,
  ticketSalesTax: 0,
  bandPayment: 1615,
  barPayment: 0,
  doorPayment: 0,
  parkingPayment: 20,
  photographyPayment: 25,
  soundPayment: 0,
  otherPayment: 0,
  barSales: 1317,
  merchSales: 170,
  posterSales: 54,
  barMerchReceipts: 0,
  barMerchSales: 0,
  barMerchTax: 0,
  totalWithdrawal: 1500,
  barBank: 300,
  bandDeposit: 285,
  totalSales: 0,
  totalExpenses: 0,
  totalDeposit: 0,
  totalProfit: 0,
  submitted: false,
};

export const closeoutTest4 = {
  step: 4,
  houseCount: 0,
  ticketTurnbacks: 0,
  noShows: 0,
  onlineSales: 3300,
  doorSales: 160,
  totalTicketsSold: 0,
  ticketSales: 0,
  ticketSalesTax: 0,
  bandPayment: 250,
  barPayment: 0,
  doorPayment: 50,
  parkingPayment: 20,
  photographyPayment: 25,
  soundPayment: 0,
  otherPayment: 0,
  barSales: 1306,
  merchSales: 120,
  posterSales: 14,
  barMerchReceipts: 0,
  barMerchSales: 0,
  barMerchTax: 0,
  totalWithdrawal: 300,
  barBank: 300,
  bandDeposit: 240,
  totalSales: 0,
  totalExpenses: 0,
  totalDeposit: 0,
  totalProfit: 0,
  submitted: false,
};

export const closeoutTest5 = {
  onlineSales: 2200,
  doorSales: 85,
  bandPayment: 1550,
  barPayment: 0,
  doorPayment: 0,
  parkingPayment: 0,
  photographyPayment: 25,
  soundPayment: 20,
  otherPayment: 0,
  barSales: 0,
  merchSales: 40,
  posterSales: 22,
  totalWithdrawal: 1445,
  barBank: 300,
  bandDeposit: 0,
  totalDeposit: 1158,
  submitted: false,
};

export const closeoutTest6 = {
  onlineSales: 2640,
  doorSales: 0,
  bandPayment: 1675,
  barPayment: 50,
  doorPayment: 0,
  parkingPayment: 20,
  photographyPayment: 25,
  soundPayment: 50,
  otherPayment: 0,
  barSales: 1074,
  merchSales: 60,
  posterSales: 20,
  totalWithdrawal: 1485,
  barBank: 300,
  bandDeposit: 0,
  totalDeposit: 0,
  submitted: false,
};

export const closeoutTest7 = {
  onlineSales: 3080,
  doorSales: 56,
  bandPayment: 1875,
  barPayment: 50,
  doorPayment: 0,
  parkingPayment: 20,
  photographyPayment: 25,
  soundPayment: 50,
  otherPayment: 0,
  barSales: 0,
  merchSales: 40,
  posterSales: 26,
  totalWithdrawal: 2175,
  barBank: 300,
  bandDeposit: 425,
  totalDeposit: 1312,
  submitted: false,
};
